export type Lifecycle = 'Growth' | 'Maturity' | 'Decline';
export type ABCClass = 'A' | 'B' | 'C';
export type Recommendation = 'Invest' | 'Optimize' | 'Consolidate' | 'Sunset';
export type Vertical = 'Healthcare' | 'Commercial' | 'Government' | 'Retail' | 'Industrial' | 'Mixed';

export interface SKU {
  id: string;
  name: string;
  line: string;
  lineIndex: number; // 0-7 for coloring
  revenue: number; // in $M
  gmPercent: number;
  lifecycle: Lifecycle;
  abcClass: ABCClass;
  sensors?: string[];
  components: number;
  sharedComponents: number;
  vertical: Vertical;
  patentProtected: boolean;
  aaadmCertified: boolean;
  yearsInPortfolio: number;
  costToServe: number; // % of revenue
  recommendation: Recommendation;
  strategic?: string; // strategic notes
  score: number; // 0-100 AI score
  confidence: 'High' | 'Medium' | 'Low';
  topReason: string;
  certifications?: string[]; // applicable ANSI/UL standards
  knownLimitations?: string; // classification caveats or compliance notes
  hvhzRated?: boolean; // Miami-Dade / HVHZ approval status
  noa?: string; // Florida NOA reference and status
}

export const PRODUCT_LINES = [
  'ASSA ABLOY Sliding',
  'ASSA ABLOY Swing',
  'ASSA ABLOY Revolving',
  'ASSA ABLOY Folding',
  'VersaMax Healthcare',
  'RECORD TSA Sliding',
  'RECORD Windcord',
  'Sensors + Accessories',
];

export const LINE_COLORS = [
  '#F2631F', // orange — primary
  '#4A9EFF', // blue
  '#3DD68C', // green
  '#F5C518', // yellow
  '#A855F7', // purple
  '#22D3EE', // cyan
  '#FB923C', // light orange
  '#F472B6', // pink
];

export const skus: SKU[] = [
  // Line 1: ASSA ABLOY Sliding Operators
  {
    id: 'SL500-R104',
    name: 'SL500 R104 (HVHZ)',
    line: 'ASSA ABLOY Sliding',
    lineIndex: 0,
    revenue: 4.2,
    gmPercent: 42,
    lifecycle: 'Growth',
    abcClass: 'A',
    sensors: ['Microwave'],
    components: 18,
    sharedComponents: 12,
    vertical: 'Commercial',
    patentProtected: true,
    aaadmCertified: true,
    yearsInPortfolio: 4,
    costToServe: 14,
    recommendation: 'Invest',
    strategic: 'Blocker/HVHZ spec',
    score: 88,
    confidence: 'High',
    topReason: 'Growth-stage A-class with HVHZ code requirement — strong market lock-in',
    certifications: ['ANSI/BHMA A156.10'],
  },
  {
    id: 'SL500-R92',
    name: 'SL500 R92 (Standard)',
    line: 'ASSA ABLOY Sliding',
    lineIndex: 0,
    revenue: 6.8,
    gmPercent: 38,
    lifecycle: 'Maturity',
    abcClass: 'A',
    sensors: ['Microwave', 'IR'],
    components: 16,
    sharedComponents: 14,
    vertical: 'Commercial',
    patentProtected: false,
    aaadmCertified: true,
    yearsInPortfolio: 9,
    costToServe: 16,
    recommendation: 'Optimize',
    score: 72,
    confidence: 'High',
    topReason: 'Highest revenue SKU in portfolio; maturity stage warrants margin optimization',
  },
  {
    id: 'SL500-R128',
    name: 'SL500 R128 (Heavy Duty)',
    line: 'ASSA ABLOY Sliding',
    lineIndex: 0,
    revenue: 2.1,
    gmPercent: 35,
    lifecycle: 'Maturity',
    abcClass: 'B',
    sensors: ['Radar'],
    components: 18,
    sharedComponents: 11,
    vertical: 'Industrial',
    patentProtected: false,
    aaadmCertified: true,
    yearsInPortfolio: 7,
    costToServe: 20,
    recommendation: 'Optimize',
    score: 58,
    confidence: 'Medium',
    topReason: 'Moderate revenue, margin below target — cost reduction opportunity exists',
  },
  {
    id: 'SL500-BP',
    name: 'SL500 Bi-Parting',
    line: 'ASSA ABLOY Sliding',
    lineIndex: 0,
    revenue: 1.4,
    gmPercent: 33,
    lifecycle: 'Maturity',
    abcClass: 'B',
    components: 20,
    sharedComponents: 10,
    vertical: 'Retail',
    patentProtected: false,
    aaadmCertified: false,
    yearsInPortfolio: 11,
    costToServe: 22,
    recommendation: 'Consolidate',
    score: 44,
    confidence: 'Medium',
    topReason: 'High component count with low shared parts — consolidation with R92 feasible',
  },
  {
    id: 'SL500-LE',
    name: 'SL500 Low Energy',
    line: 'ASSA ABLOY Sliding',
    lineIndex: 0,
    revenue: 0.8,
    gmPercent: 29,
    lifecycle: 'Decline',
    abcClass: 'C',
    components: 15,
    sharedComponents: 9,
    vertical: 'Commercial',
    patentProtected: false,
    aaadmCertified: false,
    yearsInPortfolio: 13,
    costToServe: 28,
    recommendation: 'Sunset',
    score: 18,
    confidence: 'High',
    topReason: 'Declining demand, below-threshold GM%, no unique strategic position',
  },

  // Line 2: ASSA ABLOY Swing Operators
  {
    id: 'SW60-SR',
    name: 'SW60 Slim Retrofit',
    line: 'ASSA ABLOY Swing',
    lineIndex: 1,
    revenue: 3.1,
    gmPercent: 44,
    lifecycle: 'Growth',
    abcClass: 'A',
    sensors: ['IR', 'Bluetooth'],
    components: 12,
    sharedComponents: 8,
    vertical: 'Mixed',
    patentProtected: false,
    aaadmCertified: true,
    yearsInPortfolio: 3,
    costToServe: 12,
    recommendation: 'Invest',
    score: 85,
    confidence: 'High',
    topReason: 'High-growth A-class with strong margin and retrofit market expansion',
  },
  {
    id: 'SW200-OHC',
    name: 'SW200 OHC',
    line: 'ASSA ABLOY Swing',
    lineIndex: 1,
    revenue: 5.2,
    gmPercent: 40,
    lifecycle: 'Maturity',
    abcClass: 'A',
    components: 14,
    sharedComponents: 10,
    vertical: 'Commercial',
    patentProtected: false,
    aaadmCertified: true,
    yearsInPortfolio: 8,
    costToServe: 17,
    recommendation: 'Optimize',
    score: 68,
    confidence: 'High',
    topReason: 'Core revenue driver at maturity — price realization and mix improvement needed',
  },
  {
    id: 'SW300-FE',
    name: 'SW300 Full Energy',
    line: 'ASSA ABLOY Swing',
    lineIndex: 1,
    revenue: 1.9,
    gmPercent: 36,
    lifecycle: 'Maturity',
    abcClass: 'B',
    components: 14,
    sharedComponents: 9,
    vertical: 'Government',
    patentProtected: false,
    aaadmCertified: true,
    yearsInPortfolio: 10,
    costToServe: 19,
    recommendation: 'Optimize',
    score: 52,
    confidence: 'Medium',
    topReason: 'Government vertical hold; margin pressure warrants component cost review',
  },
  {
    id: 'SW100-LE',
    name: 'SW100 Low Energy',
    line: 'ASSA ABLOY Swing',
    lineIndex: 1,
    revenue: 1.2,
    gmPercent: 31,
    lifecycle: 'Maturity',
    abcClass: 'B',
    components: 12,
    sharedComponents: 8,
    vertical: 'Commercial',
    patentProtected: false,
    aaadmCertified: false,
    yearsInPortfolio: 12,
    costToServe: 25,
    recommendation: 'Consolidate',
    score: 36,
    confidence: 'Medium',
    topReason: 'Overlaps SW200 OHC — consolidation would free shared component capacity',
  },
  {
    id: 'SW50-R',
    name: 'SW50 Residential',
    line: 'ASSA ABLOY Swing',
    lineIndex: 1,
    revenue: 0.4,
    gmPercent: 22,
    lifecycle: 'Decline',
    abcClass: 'C',
    components: 10,
    sharedComponents: 4,
    vertical: 'Commercial',
    patentProtected: false,
    aaadmCertified: false,
    yearsInPortfolio: 15,
    costToServe: 32,
    recommendation: 'Sunset',
    score: 10,
    confidence: 'High',
    topReason: 'Sub-threshold margin (22%) with declining volumes and no strategic differentiation',
  },

  // Line 3: ASSA ABLOY Revolving Doors
  {
    id: 'RD700',
    name: 'RD700 Three-Wing Revolving',
    line: 'ASSA ABLOY Revolving',
    lineIndex: 2,
    revenue: 2.8,
    gmPercent: 45,
    lifecycle: 'Growth',
    abcClass: 'A',
    components: 32,
    sharedComponents: 6,
    vertical: 'Commercial',
    patentProtected: true,
    aaadmCertified: true,
    yearsInPortfolio: 5,
    costToServe: 18,
    recommendation: 'Invest',
    score: 82,
    confidence: 'High',
    topReason: 'Premium segment growth with patent protection — flagship lobby positioning',
    certifications: ['ANSI/BHMA A156.27'],
  },
  {
    id: 'RD4-T4',
    name: 'RD4-T4 Four-Wing',
    line: 'ASSA ABLOY Revolving',
    lineIndex: 2,
    revenue: 1.6,
    gmPercent: 42,
    lifecycle: 'Maturity',
    abcClass: 'B',
    components: 35,
    sharedComponents: 6,
    vertical: 'Commercial',
    patentProtected: true,
    aaadmCertified: true,
    yearsInPortfolio: 8,
    costToServe: 21,
    recommendation: 'Optimize',
    score: 60,
    confidence: 'Medium',
    topReason: 'Good margin but complex BOM — engineering simplification would improve profitability',
  },
  {
    id: 'RD2-TWS',
    name: 'RD2 Two-Wing Speed',
    line: 'ASSA ABLOY Revolving',
    lineIndex: 2,
    revenue: 0.9,
    gmPercent: 38,
    lifecycle: 'Growth',
    abcClass: 'B',
    components: 28,
    sharedComponents: 5,
    vertical: 'Retail',
    patentProtected: true,
    aaadmCertified: false,
    yearsInPortfolio: 3,
    costToServe: 20,
    recommendation: 'Optimize',
    score: 55,
    confidence: 'Medium',
    topReason: 'Early growth trajectory — invest selectively pending market share validation',
  },

  // Line 4: ASSA ABLOY Folding Doors
  {
    id: 'FD200',
    name: 'FD200 Folding',
    line: 'ASSA ABLOY Folding',
    lineIndex: 3,
    revenue: 1.1,
    gmPercent: 34,
    lifecycle: 'Maturity',
    abcClass: 'B',
    components: 22,
    sharedComponents: 4,
    vertical: 'Retail',
    patentProtected: false,
    aaadmCertified: false,
    yearsInPortfolio: 9,
    costToServe: 23,
    recommendation: 'Optimize',
    score: 42,
    confidence: 'Medium',
    topReason: 'Below-average margin with limited shared components — targeted cost-out needed',
  },
  {
    id: 'FD100-CF',
    name: 'FD100 Compact Fold',
    line: 'ASSA ABLOY Folding',
    lineIndex: 3,
    revenue: 0.5,
    gmPercent: 28,
    lifecycle: 'Decline',
    abcClass: 'C',
    components: 18,
    sharedComponents: 3,
    vertical: 'Retail',
    patentProtected: false,
    aaadmCertified: false,
    yearsInPortfolio: 14,
    costToServe: 30,
    recommendation: 'Sunset',
    score: 14,
    confidence: 'High',
    topReason: 'Low margin, declining revenue, minimal shared components — retirement candidate',
  },

  // Line 5: VersaMax Healthcare
  {
    id: 'VM-ICU',
    name: 'VersaMax ICU',
    line: 'VersaMax Healthcare',
    lineIndex: 4,
    revenue: 3.4,
    gmPercent: 48,
    lifecycle: 'Growth',
    abcClass: 'A',
    sensors: ['Nurse Call', 'Radar'],
    components: 24,
    sharedComponents: 8,
    vertical: 'Healthcare',
    patentProtected: true,
    aaadmCertified: true,
    yearsInPortfolio: 4,
    costToServe: 13,
    recommendation: 'Invest',
    score: 94,
    confidence: 'High',
    topReason: 'Highest-scoring SKU — healthcare growth, patent moat, premium margin',
  },
  {
    id: 'VM-CCU',
    name: 'VersaMax CCU',
    line: 'VersaMax Healthcare',
    lineIndex: 4,
    revenue: 2.2,
    gmPercent: 46,
    lifecycle: 'Growth',
    abcClass: 'A',
    components: 24,
    sharedComponents: 8,
    vertical: 'Healthcare',
    patentProtected: true,
    aaadmCertified: true,
    yearsInPortfolio: 4,
    costToServe: 13,
    recommendation: 'Invest',
    score: 91,
    confidence: 'High',
    topReason: 'Critical care cardiac unit adoption accelerating — expand specification pipeline',
  },
  {
    id: 'VM-ED',
    name: 'VersaMax ED',
    line: 'VersaMax Healthcare',
    lineIndex: 4,
    revenue: 1.8,
    gmPercent: 44,
    lifecycle: 'Growth',
    abcClass: 'B',
    components: 22,
    sharedComponents: 7,
    vertical: 'Healthcare',
    patentProtected: true,
    aaadmCertified: true,
    yearsInPortfolio: 3,
    costToServe: 14,
    recommendation: 'Invest',
    score: 86,
    confidence: 'High',
    topReason: 'Emergency department footprint expanding; strong compliance selling angle',
  },
  {
    id: 'VM-OR',
    name: 'VersaMax OR',
    line: 'VersaMax Healthcare',
    lineIndex: 4,
    revenue: 1.4,
    gmPercent: 47,
    lifecycle: 'Growth',
    abcClass: 'B',
    components: 22,
    sharedComponents: 7,
    vertical: 'Healthcare',
    patentProtected: true,
    aaadmCertified: true,
    yearsInPortfolio: 3,
    costToServe: 13,
    recommendation: 'Invest',
    score: 89,
    confidence: 'High',
    topReason: 'OR sterile-field compliance requirement creates durable spec position',
  },
  {
    id: 'VM-GEN',
    name: 'VersaMax General',
    line: 'VersaMax Healthcare',
    lineIndex: 4,
    revenue: 0.9,
    gmPercent: 40,
    lifecycle: 'Maturity',
    abcClass: 'B',
    components: 20,
    sharedComponents: 7,
    vertical: 'Healthcare',
    patentProtected: false,
    aaadmCertified: true,
    yearsInPortfolio: 6,
    costToServe: 16,
    recommendation: 'Optimize',
    score: 64,
    confidence: 'Medium',
    topReason: 'Maturing healthcare general ward segment — optimize pricing and distributor mix',
  },

  // Line 6: RECORD TSA Sliding
  {
    id: 'TSA20-STD',
    name: 'TSA 20 Standard',
    line: 'RECORD TSA Sliding',
    lineIndex: 5,
    revenue: 2.6,
    gmPercent: 36,
    lifecycle: 'Maturity',
    abcClass: 'A',
    sensors: ['Microwave'],
    components: 14,
    sharedComponents: 6,
    vertical: 'Commercial',
    patentProtected: false,
    aaadmCertified: true,
    yearsInPortfolio: 8,
    costToServe: 18,
    recommendation: 'Optimize',
    score: 63,
    confidence: 'Medium',
    topReason: 'RECORD heritage A-class — platform harmonization with SL500 would unlock margin',
    certifications: ['ANSI/BHMA A156.10'],
  },
  {
    id: 'TSA21-STD',
    name: 'TSA 21 Low Energy',
    line: 'RECORD TSA Sliding',
    lineIndex: 5,
    revenue: 1.3,
    gmPercent: 33,
    lifecycle: 'Maturity',
    abcClass: 'B',
    components: 14,
    sharedComponents: 6,
    vertical: 'Commercial',
    patentProtected: false,
    aaadmCertified: false,
    yearsInPortfolio: 9,
    costToServe: 22,
    recommendation: 'Consolidate',
    score: 38,
    confidence: 'Medium',
    topReason: 'Functional overlap with SL500 Low Energy — consolidation saves dual tooling cost',
    certifications: ['ANSI/BHMA A156.10'],
  },
  {
    id: 'TSA20-AAD',
    name: 'TSA 20 AAADM',
    line: 'RECORD TSA Sliding',
    lineIndex: 5,
    revenue: 0.8,
    gmPercent: 35,
    lifecycle: 'Maturity',
    abcClass: 'B',
    components: 15,
    sharedComponents: 6,
    vertical: 'Government',
    patentProtected: false,
    aaadmCertified: true,
    yearsInPortfolio: 7,
    costToServe: 20,
    recommendation: 'Optimize',
    score: 48,
    confidence: 'Medium',
    topReason: 'AAADM certification creates government spec lock — preserve but standardize',
    certifications: ['ANSI/BHMA A156.10'],
  },
  {
    id: 'TSA22-TEL',
    name: 'TSA 22 Telescopic',
    line: 'RECORD TSA Sliding',
    lineIndex: 5,
    revenue: 1.7,
    gmPercent: 38,
    lifecycle: 'Growth',
    abcClass: 'B',
    components: 18,
    sharedComponents: 7,
    vertical: 'Commercial',
    patentProtected: false,
    aaadmCertified: true,
    yearsInPortfolio: 4,
    costToServe: 16,
    recommendation: 'Optimize',
    score: 62,
    confidence: 'Medium',
    topReason: 'Telescopic growth niche — improve GM% through BOM rationalization',
    certifications: ['ANSI/BHMA A156.10'],
  },

  // Line 7: RECORD Windcord Series
  {
    id: 'WC5400',
    name: 'Windcord 5400',
    line: 'RECORD Windcord',
    lineIndex: 6,
    revenue: 1.9,
    gmPercent: 34,
    lifecycle: 'Maturity',
    abcClass: 'B',
    components: 16,
    sharedComponents: 5,
    vertical: 'Industrial',
    patentProtected: false,
    aaadmCertified: false,
    yearsInPortfolio: 10,
    costToServe: 21,
    recommendation: 'Optimize',
    score: 46,
    confidence: 'Medium',
    topReason: 'Industrial niche maturity — price discipline and service bundle opportunity',
    hvhzRated: true,
    noa: 'FL Statewide FL41647 (Feb 2025) active with HVHZ designation. Miami-Dade NOA 21-0630.07 expired March 2025.',
  },
  {
    id: 'WC5500',
    name: 'Windcord 5500',
    line: 'RECORD Windcord',
    lineIndex: 6,
    revenue: 2.4,
    gmPercent: 37,
    lifecycle: 'Growth',
    abcClass: 'A',
    components: 16,
    sharedComponents: 5,
    vertical: 'Industrial',
    patentProtected: false,
    aaadmCertified: false,
    yearsInPortfolio: 4,
    costToServe: 17,
    recommendation: 'Optimize',
    score: 67,
    confidence: 'Medium',
    topReason: 'Growth A-class but margin below Invest threshold — push toward 40%+ GM',
    hvhzRated: false,
    knownLimitations: 'Non-impact/windload only — no HVHZ NOA — requires approved shutter system in HVHZ zones',
  },
  {
    id: 'WC-FF',
    name: 'Windcord Flip Flow',
    line: 'RECORD Windcord',
    lineIndex: 6,
    revenue: 0.7,
    gmPercent: 30,
    lifecycle: 'Growth',
    abcClass: 'C',
    components: 20,
    sharedComponents: 4,
    vertical: 'Industrial',
    patentProtected: false,
    aaadmCertified: false,
    yearsInPortfolio: 3,
    costToServe: 26,
    recommendation: 'Optimize',
    score: 32,
    confidence: 'Low',
    topReason: 'Niche growth but C-class revenue — monitor 12 months before investment decision',
  },
  {
    id: 'WC5400-LE',
    name: 'Windcord 5400 Low Energy',
    line: 'RECORD Windcord',
    lineIndex: 6,
    revenue: 0.6,
    gmPercent: 28,
    lifecycle: 'Maturity',
    abcClass: 'C',
    components: 15,
    sharedComponents: 4,
    vertical: 'Industrial',
    patentProtected: false,
    aaadmCertified: false,
    yearsInPortfolio: 11,
    costToServe: 29,
    recommendation: 'Consolidate',
    score: 22,
    confidence: 'Medium',
    topReason: 'Low-energy variant with thin margin — consolidate into WC5400 with option config',
  },

  // Line 8: Sensors + Accessories
  {
    id: 'SS-MW',
    name: 'SmartSense Microwave',
    line: 'Sensors + Accessories',
    lineIndex: 7,
    revenue: 3.8,
    gmPercent: 52,
    lifecycle: 'Growth',
    abcClass: 'A',
    components: 8,
    sharedComponents: 32,
    vertical: 'Mixed',
    patentProtected: false,
    aaadmCertified: false,
    yearsInPortfolio: 5,
    costToServe: 10,
    recommendation: 'Invest',
    score: 92,
    confidence: 'High',
    topReason: 'Highest-margin growth sensor with 32 shared component links — platform enabler',
  },
  {
    id: 'SS-RAD',
    name: 'SmartSense Radar',
    line: 'Sensors + Accessories',
    lineIndex: 7,
    revenue: 2.1,
    gmPercent: 55,
    lifecycle: 'Growth',
    abcClass: 'A',
    components: 9,
    sharedComponents: 28,
    vertical: 'Mixed',
    patentProtected: false,
    aaadmCertified: false,
    yearsInPortfolio: 4,
    costToServe: 10,
    recommendation: 'Invest',
    score: 95,
    confidence: 'High',
    topReason: 'Highest GM% in portfolio (55%) with broad cross-line compatibility',
  },
  {
    id: 'SS-IR',
    name: 'SmartSense IR',
    line: 'Sensors + Accessories',
    lineIndex: 7,
    revenue: 1.6,
    gmPercent: 48,
    lifecycle: 'Maturity',
    abcClass: 'B',
    components: 7,
    sharedComponents: 30,
    vertical: 'Mixed',
    patentProtected: false,
    aaadmCertified: false,
    yearsInPortfolio: 7,
    costToServe: 11,
    recommendation: 'Optimize',
    score: 70,
    confidence: 'High',
    topReason: 'High shared component count makes this a platform anchor — protect and upsell',
  },
  {
    id: 'CG-IOT',
    name: 'ConnectGateway IoT',
    line: 'Sensors + Accessories',
    lineIndex: 7,
    revenue: 1.2,
    gmPercent: 58,
    lifecycle: 'Growth',
    abcClass: 'B',
    components: 11,
    sharedComponents: 15,
    vertical: 'Mixed',
    patentProtected: true,
    aaadmCertified: false,
    yearsInPortfolio: 2,
    costToServe: 10,
    recommendation: 'Invest',
    score: 90,
    confidence: 'High',
    topReason: 'Highest single-SKU margin (58%) with patent protection — IoT connectivity moat',
  },
  {
    id: 'BT-AM',
    name: 'BT Access Module',
    line: 'Sensors + Accessories',
    lineIndex: 7,
    revenue: 0.9,
    gmPercent: 54,
    lifecycle: 'Growth',
    abcClass: 'B',
    components: 6,
    sharedComponents: 12,
    vertical: 'Mixed',
    patentProtected: false,
    aaadmCertified: false,
    yearsInPortfolio: 3,
    costToServe: 11,
    recommendation: 'Invest',
    score: 83,
    confidence: 'High',
    topReason: 'BLE access control trend accelerating — high-margin growth enabler',
  },
  {
    id: 'UBK',
    name: 'Universal Breakout Kit',
    line: 'Sensors + Accessories',
    lineIndex: 7,
    revenue: 1.4,
    gmPercent: 45,
    lifecycle: 'Maturity',
    abcClass: 'B',
    components: 5,
    sharedComponents: 40,
    vertical: 'Mixed',
    patentProtected: false,
    aaadmCertified: false,
    yearsInPortfolio: 8,
    costToServe: 12,
    recommendation: 'Optimize',
    score: 65,
    confidence: 'High',
    topReason: 'Highest shared-component attachment (40) — essential cross-sell anchor SKU',
  },
  {
    id: 'SSE',
    name: 'Safety Sensor Edge',
    line: 'Sensors + Accessories',
    lineIndex: 7,
    revenue: 0.8,
    gmPercent: 41,
    lifecycle: 'Maturity',
    abcClass: 'B',
    components: 4,
    sharedComponents: 38,
    vertical: 'Mixed',
    patentProtected: false,
    aaadmCertified: false,
    yearsInPortfolio: 9,
    costToServe: 13,
    recommendation: 'Optimize',
    score: 58,
    confidence: 'Medium',
    topReason: 'Safety-critical compliance item with broad cross-line fit — protect position',
  },
  {
    id: 'LP',
    name: 'Legacy Pushplate',
    line: 'Sensors + Accessories',
    lineIndex: 7,
    revenue: 0.3,
    gmPercent: 18,
    lifecycle: 'Decline',
    abcClass: 'C',
    components: 3,
    sharedComponents: 5,
    vertical: 'Commercial',
    patentProtected: false,
    aaadmCertified: false,
    yearsInPortfolio: 18,
    costToServe: 35,
    recommendation: 'Sunset',
    score: 5,
    confidence: 'High',
    topReason: 'Lowest margin SKU (18%), oldest in portfolio (18yr), no strategic role remaining',
  },
  {
    id: 'WKP',
    name: 'Wired Keypad Panel',
    line: 'Sensors + Accessories',
    lineIndex: 7,
    revenue: 0.4,
    gmPercent: 20,
    lifecycle: 'Decline',
    abcClass: 'C',
    components: 6,
    sharedComponents: 3,
    vertical: 'Commercial',
    patentProtected: false,
    aaadmCertified: false,
    yearsInPortfolio: 16,
    costToServe: 33,
    recommendation: 'Sunset',
    score: 8,
    confidence: 'High',
    topReason: 'Legacy wired technology displaced by BT/IoT — phase out by next cycle',
  },
];

// Aggregated stats
export const PORTFOLIO_STATS = {
  totalRevenue: 62.4,
  weightedAvgGM: 38.7,
  skusToRationalize: 9,
  valueAtRisk: 3.2,
  healthScore: 74,
  totalSKUs: 47,
};

export const REVENUE_BY_LINE = PRODUCT_LINES.map((line, i) => ({
  name: line,
  revenue: skus.filter((s) => s.lineIndex === i).reduce((sum, s) => sum + s.revenue, 0),
  color: LINE_COLORS[i],
}));

export const GM_BY_LINE = PRODUCT_LINES.map((line, i) => {
  const lineSkus = skus.filter((s) => s.lineIndex === i);
  const totalRev = lineSkus.reduce((sum, s) => sum + s.revenue, 0);
  const weightedGM =
    totalRev > 0
      ? lineSkus.reduce((sum, s) => sum + s.gmPercent * s.revenue, 0) / totalRev
      : 0;
  return {
    name: line.replace('ASSA ABLOY ', 'AA ').replace('RECORD ', 'RC ').replace('Sensors + Accessories', 'Sensors'),
    gm: parseFloat(weightedGM.toFixed(1)),
    color: weightedGM > 45 ? '#3DD68C' : weightedGM >= 35 ? '#F5C518' : '#EF4444',
  };
});

export const ABC_SUMMARY = [
  {
    tier: 'A',
    count: skus.filter((s) => s.abcClass === 'A').length,
    revenue: parseFloat(skus.filter((s) => s.abcClass === 'A').reduce((sum, s) => sum + s.revenue, 0).toFixed(1)),
  },
  {
    tier: 'B',
    count: skus.filter((s) => s.abcClass === 'B').length,
    revenue: parseFloat(skus.filter((s) => s.abcClass === 'B').reduce((sum, s) => sum + s.revenue, 0).toFixed(1)),
  },
  {
    tier: 'C',
    count: skus.filter((s) => s.abcClass === 'C').length,
    revenue: parseFloat(skus.filter((s) => s.abcClass === 'C').reduce((sum, s) => sum + s.revenue, 0).toFixed(1)),
  },
];
